[tool.poetry]
name = "gossip-chatserver"
version = "1.0.0"
description = "Kek"
authors = [
    "Rogov Artemiy",
    "Nikita Anchutin"
]

[tool.poetry.dependencies]
python = ">=3.11, <3.12"
pydantic = "^1.10.0"
aiohttp = "^3.8.4"
